### ISSUE TITLE
Clippy can help! (runtime)

### ISSUE THREAD

**Issue by gawdn** [spider93287/SDD-Project#10]
# Clippy can help!
## Important information
**Level**  
```diff
-runtime
```
**Error code**
```diff
-Run-time error '521': Can't open Clipboard
```
**Description**
When the form is unfocused, while loading the graph, this error is yielded.

## Visuals
![image](https://user-images.githubusercontent.com/26182503/27010693-9388a492-4eed-11e7-84c7-27544d155d52.png)

@gawdn

**Comment by edwudw** [comment]
Visual Basic 6 bug, cannot be fixed by me.
