### ISSUE TITLE
You flew so high, but in the end it didn't even matter (visual + functionality)

### ISSUE THREAD

**Issue by gawdn** [spider93287/SDD-Project#11]
# You flew so high, but in the end it didn't even matter
## Important information
**Level**  
```diff
-visual, functionality
```
**Error code**
```diff
None
```
**Description**
When any value for landing height is given, the graph displays it incorrectly (displays the landing height as zero (0))

## Visuals
![image](https://user-images.githubusercontent.com/26182503/27010700-eb4c4580-4eed-11e7-9ccf-76fc71199a31.png)

@gawdn

**Comment by edwudw** [comment]
Issue has been fixed, my first algorithm did not take into account the heightEnd difference when sending results to the graph function.
