### ISSUE TITLE
&Hello to you (unintended)

### ISSUE THREAD

**Issue by gawdn** [spider93287/SDD-Project#2]
# &Hello to you
## Important information
**Level**  
```diff
+unintended behaviour
```
**Error code**
```diff
None
```
**Description**
Inputs allow for hexadecimal input (and octal too!) in the form `&H10A` for the value `0x10A` etc.

## Visuals
![image](https://user-images.githubusercontent.com/26182503/27010555-a2cec7b8-4eea-11e7-8575-e2dab7186816.png)

@gawdn

**Comment by edwudw** [comment]
This isn't a bug. This is an unintended feature :)
