### ISSUE TITLE
Justify align one word (visual)

### ISSUE THREAD

**Issue by gawdn** [spider93287/SDD-Project#5]
# justify align one word 
## Important information
**Level**  
```diff
+visual
```
**Error code**
```diff
None
```
**Description**
Program scales incorrectly which means controls are not aligned correctly.

## Visuals
![image](https://user-images.githubusercontent.com/26182503/27010618-df8fe49c-4eeb-11e7-8cbc-d8b57fc2fecc.png)
@gawdn

**Comment by edwudw** [comment]
Don't have time to fix this.
